# ST 554 Analysis of BigData - Fianl Project
* Name: Yujin Kim
* Course: ST 554 (601) Spring 2026 Analysis of Big Data
* Assignment: Final Project

# Introduction
This project focuses on building a machine learning pipeline using PySpark to model power consumption. The goal is to predict the Power_Zone_3 variable using other environmental and operational variables.

The project consists of two main components:

(1) regression model is developed using an Elastic Net approach with cross-validation to identify the optimal model parameters. 

(2) streaming pipeline is implemented to simulate real-time data processing, where incoming data is continuously processed and predictions are generated.

The streaming system is designed to read data from a folder, apply the trained model, and output predictions along with residual values in real time.

In [63]:
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

from pyspark.ml import Pipeline
from pyspark.ml.feature import SQLTransformer, Binarizer, OneHotEncoder, VectorAssembler, PCA

from pyspark.ml.regression import LinearRegression
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder

spark = SparkSession.builder.appName("FinalProject").getOrCreate()

# 1. Fitting Model
In this step, the dataset is loaded using pandas and then converted into a Spark DataFrame. 
This is required because the project instructions specify using `pd.read_csv()` before transitioning to Spark.

The dataset contains power consumption data along with environmental variables such as temperature, humidity, and wind speed. The target variable for prediction is Power_Zone_3.

## 1.1. Data Loading

In [64]:
#Instruction: You should read this data into a standard pandas data frame using the pd.read_csv() function.
df_pd = pd.read_csv("https://www4.stat.ncsu.edu/~online/datasets/power_ml_data.csv")
df_pd.head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour
0,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386,1,0
1,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434,1,0
2,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373,1,0
3,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711,1,0
4,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964,1,0

In [65]:
#Instruction: Convert this to a spark data frame
spark_df = spark.createDataFrame(df_pd)
spark_df.printSchema()

root
 |-- Temperature: double (nullable = true)
 |-- Humidity: double (nullable = true)
 |-- Wind_Speed: double (nullable = true)
 |-- General_Diffuse_Flows: double (nullable = true)
 |-- Diffuse_Flows: double (nullable = true)
 |-- Power_Zone_1: double (nullable = true)
 |-- Power_Zone_2: double (nullable = true)
 |-- Power_Zone_3: double (nullable = true)
 |-- Month: long (nullable = true)
 |-- Hour: long (nullable = true)

In [66]:
spark_df.show(5)

+-----------+--------+----------+---------------------+-------------+------------+------------+------------+-----+----+
|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Power_Zone_3|Month|Hour|
+-----------+--------+----------+---------------------+-------------+------------+------------+------------+-----+----+
|      6.559|    73.8|     0.083|                0.051|        0.119|  34055.6962| 16128.87538| 20240.96386|    1|   0|
|      6.414|    74.5|     0.083|                 0.07|        0.085| 29814.68354| 19375.07599| 20131.08434|    1|   0|
|      6.313|    74.5|      0.08|                0.062|          0.1| 29128.10127| 19006.68693| 19668.43373|    1|   0|
|      6.121|    75.0|     0.083|                0.091|        0.096| 28228.86076| 18361.09422| 18899.27711|    1|   0|
|      5.921|    75.7|     0.081|                0.048|        0.085|  27335.6962| 17872.34043| 18442.40964|    1|   0|
+-----------+--------+----------+---------------------+-------------+------------+------------+------------+-----+----+
only showing top 5 rows

## 1.2. Data Transformation Pipeline

A series of transformations are applied to prepare the data for modeling. These transformations are implemented using PySpark MLlib and combined into a pipeline.

- The Hour variable is cast to a numeric type.
- The Hour variable is binarized to represent day and night.
- The Month variable is converted into a one-hot encoded format.
- PCA is applied to reduce dimensionality of environmental variables.
- All features are assembled into a single feature vector.


Instruction:
We are going to treat the Power_Zone_3 variable as our response variable.
We can use all of the other variables as predictors. (Imagine we know that the Power_Zone_3 reading
is going to go offline in the future and we need to be able to predict that value appropriately.)

In [67]:
#cast hour and rename response variable
sql_transformer = SQLTransformer(statement = """
    SELECT *, CAST(Hour AS DOUBLE) AS Hour_double, Power_Zone_3 AS label
    FROM __THIS__""")
#response variable Power_Zone_3 is copied and renamed as "label".

Instruction: The Hour column is likely not stored as a DoubleType. If it is not, use an SQL transformer to cast the
variable as a DoubleType.
Binarize the Hour column based on the column being less than 6.5 or not (night vs day essentially)

In [68]:
#create new binary variable
hour_binarizer = Binarizer(threshold = 6.5, inputCol = "Hour_double", outputCol = "Hour_binary")

Instruction: One-hot encode the Month column

In [69]:
month_encoder = OneHotEncoder(inputCols = ["Month"], outputCols = ["Month_encoded"])

Instruction: Run a PCA fit on the Temperature, Humidity, Wind_Speed, General_Diffuse_Flows, and
Diffuse_Flows columns.

In [70]:
#Instruction: Use a VectorAssembler() call to place these variables in a column together for use with the PCA() estimator.
pca_assembler = VectorAssembler(
    inputCols = ["Temperature", "Humidity", "Wind_Speed", "General_Diffuse_Flows", "Diffuse_Flows"],
    outputCol = "pca_input")

In [71]:
#Instruction: We’ll use two PCs in our transformation.
pca = PCA(k = 2, inputCol = "pca_input", outputCol = "pca_features") #define PCA transformer

Instruction: Use VectorAssembler() to put your predictors into a features. Use the
* two fitted PCA features
* binary Hour variable
* Power_Zone_1
* Power_Zone_2
* Month indicator variables

In [72]:
feature_assembler = VectorAssembler(
    inputCols = ["pca_features", "Hour_binary", "Power_Zone_1", "Power_Zone_2", "Month_encoded"],
    outputCol = "features")

Once fitted, then you’ll have a PCA transformer we’ll use in our pipeline.

In [73]:
lr = LinearRegression(featuresCol = "features", labelCol = "label", predictionCol = "prediction")

Instruction: The transformations below should each use an MLlib function that can be put into a pipeline

In [74]:
#Build full pipeline
pipeline = Pipeline(stages = [sql_transformer, hour_binarizer, month_encoder, pca_assembler, pca, feature_assembler, lr])

## 1.3. Model Training (Elastic Net + CV)
An Elastic Net regression model is trained using PySpark's LinearRegression. 
Cross-validation is applied to determine the optimal combination of hyperparameters.
The model is evaluated using 5-fold cross-validation, with RMSE as the performance metric.

Instruction: Now you’ll then use the CrossValidator() function and the LinearRegression() function to fit an
elastic net model.

In [75]:
#define evaluator of model performance
evaluator = RegressionEvaluator(labelCol = "label", predictionCol = "prediction", metricName = "rmse")

Instruction: You should do the following grid for the regParam and elasticNetParam: All combinations of
* regParam: 0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1
* elasticNetParam: 0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1

In [76]:
#define parameter grid
param_values = [0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.98, 0.99, 1]

param_grid = (ParamGridBuilder().addGrid(lr.regParam, param_values).addGrid(lr.elasticNetParam, param_values).build())

Instruction: Now fit the model using 5-fold CV with rmse as your criterion!

In [77]:
#set up 5-fold cross validation
cv = CrossValidator(estimator = pipeline,
                    estimatorParamMaps = param_grid,
                    evaluator = evaluator,
                    numFolds = 5,
                    seed = 123)

In [78]:
#fit the model
cv_model = cv.fit(spark_df)

26/04/29 14:44:35 WARN Instrumentation: [f1571adc] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:35 WARN Instrumentation: [f1571adc] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:36 WARN Instrumentation: [406d6f53] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:36 WARN Instrumentation: [406d6f53] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:37 WARN Instrumentation: [a23d5c21] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:38 WARN Instrumentation: [a23d5c21] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:38 WARN Instrumentation: [1c81dd93] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:39 WARN Instrumentation: [1c81dd93] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:40 WARN Instrumentation: [b8c6a70b] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:40 WARN Instrumentation: [b8c6a70b] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:41 WARN Instrumentation: [912d38a6] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:41 WARN Instrumentation: [912d38a6] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:42 WARN Instrumentation: [2fcb4e1c] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:42 WARN Instrumentation: [2fcb4e1c] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:43 WARN Instrumentation: [4de0df8f] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:43 WARN Instrumentation: [4de0df8f] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:44 WARN Instrumentation: [e0e9d305] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:44 WARN Instrumentation: [e0e9d305] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:45 WARN Instrumentation: [6d7467b0] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:45 WARN Instrumentation: [6d7467b0] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:44:46 WARN Instrumentation: [7a8d0edf] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:44:46 WARN Instrumentation: [7a8d0edf] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:29 WARN Instrumentation: [37ad06e8] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:29 WARN Instrumentation: [37ad06e8] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:30 WARN Instrumentation: [72d65da1] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:30 WARN Instrumentation: [72d65da1] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:31 WARN Instrumentation: [dac69cd4] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:31 WARN Instrumentation: [dac69cd4] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:31 WARN Instrumentation: [fedccd09] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:32 WARN Instrumentation: [fedccd09] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:32 WARN Instrumentation: [ea8dc4cc] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:32 WARN Instrumentation: [ea8dc4cc] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:33 WARN Instrumentation: [7df1b7f2] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:33 WARN Instrumentation: [7df1b7f2] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:34 WARN Instrumentation: [c825fd93] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:34 WARN Instrumentation: [c825fd93] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:35 WARN Instrumentation: [a5e3bc92] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:35 WARN Instrumentation: [a5e3bc92] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:36 WARN Instrumentation: [558985d2] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:36 WARN Instrumentation: [558985d2] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:37 WARN Instrumentation: [8b8639b3] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:37 WARN Instrumentation: [8b8639b3] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:46:37 WARN Instrumentation: [238c4672] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:46:38 WARN Instrumentation: [238c4672] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:13 WARN Instrumentation: [b03d2ecc] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:13 WARN Instrumentation: [b03d2ecc] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:14 WARN Instrumentation: [a9f7b52d] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:14 WARN Instrumentation: [a9f7b52d] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:14 WARN Instrumentation: [56255a5b] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:15 WARN Instrumentation: [56255a5b] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:15 WARN Instrumentation: [c4550398] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:15 WARN Instrumentation: [c4550398] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:16 WARN Instrumentation: [ec531419] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:16 WARN Instrumentation: [ec531419] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:17 WARN Instrumentation: [47ca02d8] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:17 WARN Instrumentation: [47ca02d8] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:18 WARN Instrumentation: [a3afbcf4] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:18 WARN Instrumentation: [a3afbcf4] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:19 WARN Instrumentation: [4355ee31] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:19 WARN Instrumentation: [4355ee31] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:20 WARN Instrumentation: [c00c6e28] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:20 WARN Instrumentation: [c00c6e28] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:20 WARN Instrumentation: [a0d9f4e6] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:21 WARN Instrumentation: [a0d9f4e6] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:48:21 WARN Instrumentation: [861966d5] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:48:21 WARN Instrumentation: [861966d5] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:00 WARN Instrumentation: [f15ce7ec] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:00 WARN Instrumentation: [f15ce7ec] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:01 WARN Instrumentation: [90cf0df2] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:01 WARN Instrumentation: [90cf0df2] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:02 WARN Instrumentation: [69271192] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:02 WARN Instrumentation: [69271192] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:03 WARN Instrumentation: [75f70433] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:03 WARN Instrumentation: [75f70433] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:04 WARN Instrumentation: [3de24e97] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:04 WARN Instrumentation: [3de24e97] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:05 WARN Instrumentation: [079bd91b] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:05 WARN Instrumentation: [079bd91b] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:06 WARN Instrumentation: [1fbe5222] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:06 WARN Instrumentation: [1fbe5222] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:07 WARN Instrumentation: [1070a288] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:07 WARN Instrumentation: [1070a288] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:07 WARN Instrumentation: [595923c9] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:08 WARN Instrumentation: [595923c9] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:08 WARN Instrumentation: [c619b3b9] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:08 WARN Instrumentation: [c619b3b9] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:50:09 WARN Instrumentation: [b21fe20d] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:50:09 WARN Instrumentation: [b21fe20d] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:43 WARN Instrumentation: [d2b7b490] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:43 WARN Instrumentation: [d2b7b490] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:44 WARN Instrumentation: [82108148] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:44 WARN Instrumentation: [82108148] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:44 WARN Instrumentation: [2a87a48a] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:44 WARN Instrumentation: [2a87a48a] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:45 WARN Instrumentation: [12d97ca3] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:45 WARN Instrumentation: [12d97ca3] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:46 WARN Instrumentation: [3f582884] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:46 WARN Instrumentation: [3f582884] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:47 WARN Instrumentation: [ccedda6e] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:47 WARN Instrumentation: [ccedda6e] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:48 WARN Instrumentation: [42c9cf86] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:48 WARN Instrumentation: [42c9cf86] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:48 WARN Instrumentation: [6dbb7f76] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:49 WARN Instrumentation: [6dbb7f76] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:49 WARN Instrumentation: [e7f68a45] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:49 WARN Instrumentation: [e7f68a45] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:50 WARN Instrumentation: [1454b5e0] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:50 WARN Instrumentation: [1454b5e0] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.
26/04/29 14:51:51 WARN Instrumentation: [f462de21] regParam is zero, which might cause numerical instability and overfitting.
26/04/29 14:51:51 WARN Instrumentation: [f462de21] Cholesky solver failed due to singular covariance matrix. Retrying with Quasi-Newton solver.

Instruction: Report the optimal values chosen for the tuning parameters

In [79]:
#report optimal tuning parameters
best_model = cv_model.bestModel
best_lr_model = best_model.stages[-1]

best_reg_param = best_lr_model.getRegParam()
best_elastic_net_param = best_lr_model.getElasticNetParam()

print("Best regParam:", best_reg_param)
print("Best elasticNetParam:", best_elastic_net_param)

Best regParam: 0.05
Best elasticNetParam: 0.1

Instruction: Report the CV error

In [80]:
# cv_model.avgMetrics stores the average CV RMSE for each parameter combination. The smallest value corresponds to the optimal CV error.
cv_errors = cv_model.avgMetrics
best_cv_error = min(cv_errors)

print("Best CV RMSE:", best_cv_error)

Best CV RMSE: 2147.8113505767924

## 1.4. Model Evaluation
After training, the model is evaluated on the training dataset. 
Predictions are generated and compared with actual values to compute RMSE.

Instruction: Report the training set RMSE (as done in the notes) by using your fitted model as a transformer and
evaluating on the entire training set

In [81]:
# Apply the final selected model to the training data
training_predictions = cv_model.transform(spark_df)
training_rmse = evaluator.evaluate(training_predictions)

print("Training RMSE:", training_rmse)

Training RMSE: 2147.0973169293934

Instruction: Take the outputted transformations from the model (the predictions) and create a residual column
(label - prediction). The .withColumn() method is handy here. Print out a data frame with these
residuals, the label column, and the predictions

In [82]:
# Create a residual column from the prediction results
training_predictions_with_residuals = training_predictions.withColumn("residual", F.col("label") - F.col("prediction"))

training_predictions_with_residuals.select("label", "prediction", "residual").show(20)

+-----------+------------------+------------------+
|      label|        prediction|          residual|
+-----------+------------------+------------------+
|20240.96386|20878.850660788543| -637.886800788543|
|20131.08434| 18660.22726654401|1470.8570734559908|
|19668.43373| 18204.75215311454|1463.6815768854613|
|18899.27711|17590.648498339142|1308.6286116608571|
|18442.40964|16997.301986456878| 1445.107653543124|
|18130.12048|16517.686723494306|1612.4337565056958|
|17945.06024|16093.246141053509|  1851.81409894649|
|17459.27711|15722.695360253945| 1736.581749746054|
|17025.54217|15271.043828662865|1754.4983413371356|
|16794.21687|14938.348764665692| 1855.868105334308|
|16638.07229|14652.383721423883|1985.6885685761172|
|16395.18072|14414.900662730442|1980.2800572695578|
|16117.59036|14082.889275686905|2034.7010843130956|
| 15822.6506| 13624.88209143617|2197.7685085638313|
|15672.28916|13450.340775468403| 2221.948384531597|
|15597.10843| 13302.24639456202|  2294.86203543798|
|15510.36145|13154.825587153266|2355.5358628467347|
|15336.86747|12995.123971843515| 2341.743498156484|
|15140.24096|12758.865076730794|2381.3758832692056|
|15059.27711|12674.919344083459| 2384.357765916542|
+-----------+------------------+------------------+
only showing top 20 rows

# 2. Streaming Part
There is another file available at: https://www4.stat.ncsu.edu/~online/datasets/power_streaming_data.csv

Download this file and store it where your .py file you’ll create can find it. We’ll be randomly sampling rows from this to output to .csv files that you’ll be reading in.

In [83]:
import pandas as pd
import os

In [84]:
#read sreaming data
stream_pd = pd.read_csv("https://www4.stat.ncsu.edu/~online/datasets/power_streaming_data.csv")

In [85]:
#Save original file for streaming
stream_pd.to_csv("power_streaming_data.csv", index = False)
stream_pd.head()

,Temperature,Humidity,Wind_Speed,General_Diffuse_Flows,Diffuse_Flows,Power_Zone_1,Power_Zone_2,Power_Zone_3,Month,Hour
0,4.805,76.2,0.081,0.059,0.134,20421.26582,12908.20669,14590.84337,1,3
1,4.212,78.3,0.081,0.117,0.082,21393.41772,13575.68389,14862.65060,1,5
2,4.304,76.0,0.082,0.048,0.152,19983.79747,12342.85714,13492.04819,1,7
3,4.489,74.3,0.082,0.081,0.119,18167.08861,11551.36778,11600.96386,1,7
4,4.509,74.5,0.084,6.643,6.494,19837.97468,11945.28875,11178.79518,1,8

## 2.1. Reading a Stream
A streaming DataFrame is created by monitoring a folder where CSV files are continuously added. 
The schema is predefined to ensure consistency with the training data.


Instruction: We’re going to read in a stream in the form of .csv files. Create a folder where you will be sending
your .csv files.

In [86]:
#generate folder for Streaming file
stream_folder = "stream_folder"
os.makedirs(stream_folder, exist_ok = True)

Instruction: Setup the schema for the stream (you can use the schema from the original data as we did in hw 10)

In [87]:
stream_schema = spark_df.schema

Instruction: Set up the readStream. Be sure to add header = True as you’ll likely be outputting files with a
header and we don’t need to read that in.

In [88]:
stream_df = spark.readStream.option("header", True).schema(stream_schema).csv(stream_folder)

## 2.2. Transform / Aggregation Step
The trained model is applied to incoming streaming data to generate predictions. A residual column is also calculated.


Instruction: Now, we’ll do two separate things on the stream and join them together:

Instruction: With your stream, use your model transformer to obtain predictions from the incoming data. On
the resulting predictions also create a residual column as noted in the previous section (return
only the label, prediction and residual columns from this part)

In [89]:
#Apply the trained model to the stream
stream_predictions = cv_model.transform(stream_df)

In [90]:
#create residual column
stream_predictions_residual = stream_predictions.withColumn("residual", F.col("label") - F.col("prediction"))

In [91]:
#Select only the required columns from the prediction results
stream_prediction_output = stream_predictions_residual.select("label", "prediction", "residual")

Instruction: We can use our stream more than once! With another transformation on the (original) stream, modify the response variable to be called label.

In [92]:
#Create a label column from the original stream
stream_label = stream_df.withColumnRenamed("Power_Zone_3", "label")

Instruction: Now join your above transform with this stream based on the label variable which should be common to both!

In [93]:
#Join the results of the two stream transformations
joined_stream = stream_prediction_output.join(stream_label, on = "label")

## 2.3. Writing Step
The results are written to the console using append mode. The streaming query runs continuously and updates as new data arrives.

Instruction: Now write your stream to the console using the append output mode.

In [112]:
query = joined_stream.writeStream.outputMode("append").format("console").start()

26/04/29 15:14:26 WARN ResolveWriteToStream: Temporary checkpoint location created which is deleted normally when the query didn't fail: /tmp/temporary-93a9a406-f303-404a-8497-56a3831b9199. If it's required to delete it under any circumstances, please set spark.sql.streaming.forceDeleteTempCheckpointLocation to true. Important to know deleting temp checkpoint folder is best effort.
26/04/29 15:14:26 WARN ResolveWriteToStream: spark.sql.adaptive.enabled is not supported in streaming DataFrames/Datasets and will be disabled.

-------------------------------------------
Batch: 0
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|          residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|14833.73494|16612.509269396956|-1778.774329396956|      13.07|   47.75|     4.921|                370.3|        382.3| 32178.22785| 21082.06687|    1|  10|
|15832.64556|18701.019006447743|-2868.373446447742|      21.57|    86.9|     0.277|                0.066|        0.141| 38548.67257| 25682.74428|    9|  22|
|11178.75383| 16298.40294417972| -5119.64911417972|      22.77|   66.76|     4.917|                609.3|         89.3| 37261.59292| 25345.94595|    9|  11|
|6949.339736|6630.2307447334515| 319.1089912665484|      11.59|    82.0|     0.079|                  9.0|         8.69| 23221.29278| 17416.38539|   12|   8|
|13385.08682|12065.552889029694|1319.5339309703068|       21.0|    80.4|     4.916|                0.069|        0.137| 26614.51327| 14852.80665|    9|   4|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 1
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|          residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|22237.09091|20350.128910895946|1886.9619991040527|       16.4|    73.6|     0.081|                0.033|        0.126| 33772.57266| 18663.54379|    4|  23|
|10457.87234| 11321.22982307218|-863.3574830721809|      18.51|    90.3|     0.066|                31.55|        26.35| 30262.05689| 20236.92946|   10|   8|
|14260.64516| 13921.44112310072|339.20403689928025|        9.8|    87.9|     0.077|                0.044|        0.148| 23946.89362| 13254.87805|    3|   5|
|16719.75684|17474.943427733575|-755.1865877335767|       19.1|    81.2|     0.071|                0.066|        0.104| 39595.27352| 23564.31535|   10|  22|
|26986.33846|26878.481721933196|107.85673806680279|      20.65|    85.4|     0.066|                0.048|        0.141| 43765.82781| 25409.56341|    6|  23|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 2
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|          residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|16170.96774| 15621.30868919299| 549.6590508070094|      17.37|    80.2|     0.075|                0.044|        0.126| 26373.44681| 15398.78049|    3|   0|
|25612.25806|25998.167503346493|-385.9094433464925|      15.72|    80.4|     4.913|                0.029|        0.141| 44492.93617| 26191.46341|    3|  20|
|14932.04819|15592.446747920289| -660.398557920289|      6.539|    82.8|     0.087|                0.073|        0.137|  25415.6962|  15621.8845|    1|   6|
|15230.71357|14905.804748449185|324.90882155081454|      15.78|   50.87|     0.084|                455.2|        39.67| 29251.52542| 16201.82371|    2|  10|
|9465.775076|  12881.0054748382|-3415.230398838201|      20.33|   65.58|     0.084|                133.9|        114.0| 32644.20131| 25745.22822|   10|  10|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 3
-------------------------------------------
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|          residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|14707.74194|14403.879450149909|303.86248985009115|      11.85|    86.5|     0.083|                0.055|        0.145| 24486.12766| 14703.65854|    3|   5|
|13485.10725|12211.077036524324|1274.0302134756748|      21.12|    73.1|      4.92|                0.066|        0.115| 26614.51327| 16207.48441|    9|   4|
|27072.60188|25726.978070848905|1345.6238091510932|      28.67|   68.46|     4.906|                685.0|        309.0|  41106.3263| 28598.52165|    8|  11|
|10357.59036| 9424.177045303246| 933.4133146967542|      18.66|    80.7|     0.067|                0.044|        0.148| 21815.38462| 15906.19835|   11|   3|
|22053.41538| 15647.96560601357| 6405.449773986429|      27.24|   56.77|     4.921|                516.1|        117.7| 29035.23179| 17565.90437|    6|  17|
+-----------+------------------+------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 4
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|27969.40439|25823.704592556678| 2145.6997974433216|      27.31|    71.6|     4.903|                227.0|        177.0| 39066.99223| 28165.15312|    8|  17|
|37331.54812| 32549.99709930396|  4781.551020696039|      27.89|   45.82|     4.911|                0.091|        0.119| 41608.50498| 28951.89873|    7|  23|
|15770.60241|15452.549530817114|  318.0528791828856|       8.06|    79.7|     0.084|                0.081|        0.111| 25154.43038| 15793.31307|    1|   1|
| 11333.4413|14062.712687266952| -2729.271387266952|      15.88|    79.2|     0.082|                 76.9|        68.96| 24324.19672| 15410.52632|    5|   6|
|15323.22581|16540.513567030517|-1217.2877570305172|      15.92|    57.4|     0.082|                207.3|        191.3| 31692.25532|     19650.0|    3|  17|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 5
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
| 12527.2509|11327.123125349479| 1200.1277746505202|      16.37|    74.8|     0.073|                0.055|        0.133| 29499.61977| 25321.87788|   12|  23|
|20655.54656|20767.899636059046|-112.35307605904745|       24.1|   64.78|     4.923|                148.8|        120.1| 37355.01639|  23550.4644|    5|  18|
|18083.85542|19802.751165445756| -1718.895745445756|      18.84|    74.5|     0.076|                0.084|        0.041| 38978.46154| 32095.04132|   11|  19|
|11647.35678|12315.886320146232| -668.5295401462317|       13.3|    74.2|     0.071|                0.037|        0.152| 23351.18644| 15038.29787|    2|   7|
|40536.90377|36332.355422170986|  4204.548347829012|      28.61|   36.18|     4.911|                0.106|        0.122| 47553.48837| 30649.36709|    7|  22|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 6
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|9756.144578| 8490.931672052495| 1265.2129059475046|      18.64|    78.7|     0.069|                0.055|        0.182| 20430.76923|  15028.5124|   11|   6|
|9968.787515|11093.347970198074|-1124.5604551980741|      16.63|   56.38|     0.077|                229.5|        222.0| 30880.60837| 25947.83676|   12|  16|
|16145.36683|16573.643476826823| -428.2766468268219|      12.47|   40.53|     0.088|                212.6|        231.3|  31557.9661| 18900.91185|    2|  17|
|14000.96386|10183.927270148672| 3817.0365898513282|       10.2|    87.9|     0.081|                0.037|        0.111| 16216.70886| 17124.62006|    1|   3|
|33306.77824| 32982.38487519455|  324.3933648054517|      26.41|   46.22|     4.913|                0.073|        0.074| 42278.27243| 29198.73418|    7|  23|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 7
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|21356.30769|16237.546341457217|  5118.761348542785|      24.82|   68.28|     4.925|                905.0|         56.8| 31101.45695| 17681.91268|    6|  13|
|25928.86154| 27591.43228279647|-1662.5707427964699|      20.94|    77.7|      0.07|                0.048|        0.133| 42265.43046| 24144.69854|    6|   1|
|6876.144578| 5364.060196610302| 1512.0843813896981|      14.46|    81.5|     0.071|                0.051|        0.111| 18664.61538| 12246.69421|   11|   7|
|16811.56627|15477.594426083882|  1333.971843916117|      11.48|    76.8|     0.077|                 0.07|        0.145|  24947.8481| 17190.27356|    1|   0|
| 17769.7166|15355.545306336391| 2414.1712936636086|      24.28|   49.45|     0.072|                809.0|         56.5| 31261.37705| 19263.15789|    5|  14|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 8
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|16762.38245| 18534.62414471595|-1772.2416947159472|      20.87|    75.7|      0.07|                101.6|        40.38| 27553.38513| 19045.40655|    8|   7|
|14171.33668|13470.665246277125|   700.671433722875|      11.37|   66.04|     4.914|                0.051|        0.108| 22686.10169|  13178.1155|    2|   3|
|9964.337349| 9785.419605375331| 178.91774362466822|       17.7|   52.99|     0.077|                0.059|        0.089| 22190.76923| 17163.22314|   11|   2|
|10608.04903|12930.879513945694| -2322.830483945694|      19.99|    89.1|      4.91|                171.4|        46.64| 31023.71681| 19126.40333|    9|   8|
|18731.56627|13634.225941740353|  5097.340328259646|      20.95|   61.77|     0.068|                525.7|         72.2| 32172.30769| 25672.31405|   11|  12|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 9
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|14812.25806|14289.486976628223|  522.7710833717774|       9.42|    82.8|     0.081|                0.022|        0.148| 24339.06383|  14469.5122|    3|   5|
|16579.69605| 16018.24530502752|  561.4507449724788|       20.2|    78.9|     4.916|                0.059|        0.137| 37257.24289| 23187.13693|   10|  22|
|24562.49246|25882.884451599675| -1320.391991599674|      13.15|   55.61|     0.081|                 8.51|         8.46| 43932.20339|  25688.7538|    2|  19|
|40380.25105|32291.568592675627|  8088.682457324372|      36.25|   21.34|     4.907|                124.4|        128.1| 42106.04651| 29692.40506|    7|  19|
|18526.52308|21027.901704932126|-2501.3786249321274|      22.25|    79.9|     0.066|                200.6|        155.0| 36085.82781| 22456.96466|    6|  14|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 10
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|16727.27273|18836.600785506038|-2109.3280555060373|      17.98|   57.87|     0.087|                662.9|        62.88| 33741.57158| 19902.64766|    4|  10|
|23599.74922| 24240.36348800409| -640.6142680040903|      26.54|   51.25|     4.903|                251.6|        215.6| 37462.37514| 24021.54171|    8|  17|
|15780.66332|16374.517547286918| -593.8542272869181|      16.19|   54.62|     0.082|                573.9|        608.9| 33772.88136| 21957.44681|    2|  11|
|17262.27692|20586.400788891413|-3324.1238688914127|      22.28|   42.34|     0.084|                211.2|        172.4| 35831.52318| 20484.82328|    6|  12|
|16897.56895| 14540.24128203971| 2357.3276679602914|      25.87|   52.92|     0.263|                710.0|        147.3| 35821.59292| 20709.35551|    9|  13|
|15437.21489|17231.902149028036|-1794.6872590280364|      14.64|    78.8|     0.086|                0.048|        0.145| 38211.40684| 31161.70604|   12|  19|
|12634.83871|14586.613922206028|-1951.7752122060283|      16.45|    79.2|     0.089|                313.6|        305.3| 29559.82979| 18673.17073|    3|   8|
|14625.54217|13185.451601924278| 1440.0905680757223|      10.42|    81.3|     0.075|                0.073|         0.13| 21685.06329| 14250.45593|    1|   1|
|15597.10843| 17452.86490312432|-1855.7564731243183|       9.73|   63.47|     0.086|                365.7|        44.35| 31989.87342| 20855.92705|    1|  11|
|15183.67347|18073.497274081492| -2889.823804081492|       16.6|   57.14|     0.085|                5.995|         5.93| 39385.55133| 32660.32525|   12|  17|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 11
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|10364.49848|12595.411111170388|-2230.9126311703876|      20.62|    78.9|     4.919|                218.1|        176.6| 32694.61707|  26174.6888|   10|  11|
|18615.90361| 13411.60365495819|  5204.299955041812|      21.23|   59.91|     0.071|                503.8|         72.8| 31895.38462| 24735.12397|   11|  13|
|18635.63636|17933.185251147836|  702.4511088521649|      14.66|    89.6|     0.066|                0.081|        0.178| 27479.35414| 15276.17108|    4|   0|
|12984.80243|13524.696903378624| -539.8944733786248|      21.93|   46.92|     4.951|                584.6|        38.93| 35694.35449| 21723.23651|   10|  10|
|30854.56067|30244.462558460276|  610.0981115397226|      31.08|   47.56|     4.919|                860.0|         86.0| 41442.65781| 28196.20253|    7|  13|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 12
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|17505.54217|14025.792025452492|  3479.750144547508|      22.28|   50.37|     0.074|                360.2|        110.1| 32695.38462| 24024.79339|   11|  15|
|24237.74295|25323.833604168176|-1086.0906541681761|      25.01|   66.72|     4.923|                250.4|        190.9| 38907.16981| 25268.42661|    8|  11|
|13833.25301|13194.510750588359|  638.7422594116415|      18.11|   41.89|      0.09|                0.037|        0.148| 21915.94937| 13057.75076|    1|   4|
|13338.01839|15466.969046336299|-2128.9506563362993|      32.49|   26.71|     4.924|                604.3|         83.8| 36293.09735| 22846.15385|    9|  15|
|9404.081633|12001.316857547934| -2597.235224547934|      14.06|   69.08|     0.083|                116.2|        117.9| 31342.96578| 26706.35164|   12|  14|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 13
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
| 16106.0241|14738.266242867014| 1367.7578571329868|      10.84|    78.4|     0.073|                0.062|        0.156| 23914.93671|  16132.5228|    1|   0|
| 22308.3871| 21173.35663028281| 1135.0304697171887|      11.27|    80.3|     0.075|                0.048|        0.189| 37292.93617| 21878.04878|    3|  22|
|10501.14573|10489.951535043643| 11.194194956357023|      11.39|   65.58|     4.916|                0.059|        0.111|  20764.0678| 12634.65046|    2|   7|
| 12039.3921|14426.658154226096|-2387.2660542260965|      22.56|   69.68|     4.916|                114.0|         89.4| 35020.04376|  25678.0083|   10|  11|
|22188.82591| 20643.65930021552|  1545.166609784479|      19.11|   51.87|     0.083|                0.084|        0.093| 36347.80328| 21860.06192|    5|  23|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 14
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|16809.31563|15237.493981502948| 1571.8216484970526|      22.71|    84.7|     0.279|                0.073|        0.119| 31119.29204| 18972.97297|    9|   0|
|24670.84337|23199.509642099547| 1471.3337279004518|      16.01|   55.27|     4.922|                0.066|        0.119| 39584.81013| 22924.01216|    1|  19|
|16168.00817|13966.092819916636| 2201.9153500833636|      25.53|   61.79|     0.309|                613.7|         70.2| 34438.93805| 19145.11435|    9|  15|
|19828.36364|18408.683834873416| 1419.6798051265832|      16.32|    83.3|     0.064|                0.044|        0.193| 28235.78041| 15441.14053|    4|   0|
|13932.25741|16147.020940692137|-2214.7635306921366|      22.21|    89.2|     4.917|                205.4|        177.0| 36293.09735| 23516.00832|    9|  14|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 15
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|15863.22581|17560.464783144576|-1697.2389731445764|      16.63|   57.33|     0.083|                309.5|        285.8| 33934.97872| 21095.12195|    3|  15|
|27433.73041|25680.692896958084|  1753.037513041916|       27.6|   68.69|     4.921|                821.0|         82.2| 40767.50277| 26800.42239|    8|  13|
|9726.770708|11438.019094898513|-1711.2483868985128|      16.83|   58.28|     0.087|                455.5|        163.7|     32000.0| 25885.24087|   12|  13|
|    21657.6|21878.227727521422|-220.62772752142337|      22.88|   42.77|      0.08|                359.8|        367.2| 38806.88742| 23942.61954|    6|  18|
|13889.03226|13226.882688917509|  662.1495710824911|      12.82|    86.1|     0.089|                0.018|        0.174| 22666.21277| 14008.53659|    3|   4|
|  12436.231| 14416.56104424752| -1980.330044247521|      20.76|    84.8|     0.067|                27.31|        23.58| 34881.40044|  22847.3029|   10|  15|
|    27520.0|25713.820267078525|  1806.179732921475|      15.47|    82.4|     0.073|                0.011|        0.122| 42037.45963|  21988.5947|    4|  21|
|16897.56895| 14540.24128203971| 2357.3276679602914|      25.87|   52.92|     0.263|                710.0|        147.3| 35821.59292| 20709.35551|    9|  13|
|16897.56895| 14540.24128203971| 2357.3276679602914|      25.87|   52.92|     0.263|                710.0|        147.3| 35821.59292| 20709.35551|    9|  13|
|16897.56895| 14540.24128203971| 2357.3276679602914|      25.87|   52.92|     0.263|                710.0|        147.3| 35821.59292| 20709.35551|    9|  13|
|28432.46862|29928.643902418844|-1496.1752824188443|      34.22|   28.71|     4.909|                330.7|         88.4| 39050.63123|  28055.6962|    7|  18|
|16990.55276| 18001.89030393926|-1011.3375439392621|       14.4|   66.61|     0.096|                193.8|        191.5| 33516.61017| 19696.04863|    2|  15|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 16
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|27391.59875| 26923.95746052033|  467.6412894796704|      29.76|   45.28|     4.908|                831.0|        38.63| 42263.44062| 28990.07392|    8|  14|
|12751.36778|10137.671287130483|  2613.696492869518|      17.83|    87.8|     4.921|                0.062|        0.141| 26165.77681| 14620.33195|   10|   5|
|17780.36364|18997.703834168104| -1217.340194168104|      16.33|    78.7|     0.071|                170.6|        155.9| 33456.36168|  15481.4664|    4|  15|
|25995.23511|26446.129344114473|-450.89423411447206|      29.74|   44.38|     4.908|                671.0|        37.98| 41099.93341|  27834.4245|    8|  15|
|21533.53846| 20562.07618121968|    971.46227878032|      24.28|   60.35|     0.069|                427.4|        454.3| 37484.50331| 22834.92723|    6|  17|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

-------------------------------------------
Batch: 17
-------------------------------------------
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|      label|        prediction|           residual|Temperature|Humidity|Wind_Speed|General_Diffuse_Flows|Diffuse_Flows|Power_Zone_1|Power_Zone_2|Month|Hour|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+
|12372.03647|14182.977445071983|-1810.9409750719842|      21.43|    71.6|     4.925|                426.5|        267.7| 36979.95624| 23470.95436|   10|  12|
|16145.36683|16573.643476826823| -428.2766468268219|      12.47|   40.53|     0.088|                212.6|        231.3|  31557.9661| 18900.91185|    2|  17|
|16145.36683|16573.643476826823| -428.2766468268219|      12.47|   40.53|     0.088|                212.6|        231.3|  31557.9661| 18900.91185|    2|  17|
|16145.36683|16573.643476826823| -428.2766468268219|      12.47|   40.53|     0.088|                212.6|        231.3|  31557.9661| 18900.91185|    2|  17|
|24197.78894| 22198.67729929272| 1999.1116407072768|      13.22|   69.03|      0.08|                0.059|        0.137| 38324.74576| 22610.33435|    2|  22|
|20945.45455|22261.205811158477|-1315.7512611584789|      26.92|    70.8|     4.903|                0.066|         0.13| 29707.79134| 22082.78775|    8|   2|
|14550.62762| 18332.71086989731|-3782.0832498973105|       20.1|    74.9|     4.919|                115.8|        101.4| 21649.43522| 14191.13924|    7|   7|
+-----------+------------------+-------------------+-----------+--------+----------+---------------------+-------------+------------+------------+-----+----+

# 3. Produce Data
A separate Python script is used to simulate streaming data. 
The script randomly samples rows from the original dataset and writes them as CSV files into the streaming folder at fixed intervals.


Instruction: You should have the file we’ll use for streaming data downloaded and in a place you can locate. Create a .py file that reads that into a pandas (regular) data frame and does the following.

In [113]:
for q in spark.streams.active:
    q.stop()

26/04/29 15:18:25 WARN DAGScheduler: Failed to cancel job group 60af8706-3ea5-4fc3-a94f-723b7ca47d58. Cannot find active jobs for it.
26/04/29 15:18:26 WARN DAGScheduler: Failed to cancel job group 60af8706-3ea5-4fc3-a94f-723b7ca47d58. Cannot find active jobs for it.

In [114]:
spark.streams.active

[]

# Conclusion
In this project, a complete machine learning and streaming pipeline was developed using PySpark. 
The Elastic Net regression model demonstrated the ability to predict power consumption effectively based on environmental variables.

The streaming component simulated real-time data processing, showing how a trained model can be applied dynamically to incoming data. 
The project provides practical experience with distributed data processing, machine learning pipelines, and streaming systems using Spark.

In [111]:
import glob

for f in glob.glob("stream_folder/*.csv"):
    os.remove(f)